server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: p4Y2!qmvDTJd3JzZbjz9
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      scripts:
        - classpath:init.sql
