server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: beverage-service
          uri: lb://beverage-service
          predicates:
            - Path=/beverages/**
        - id: user-beverage-service
          uri: lb://user-beverage-service
          predicates:
            - Path=/user-beverages/**

jwt:
  secret: TuSecretoMuyLargo_DeAlMenos_32Bytes_ParaHS256
  expiration: 3600000