services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4Y2!qmvDTJd3JzZbjz7
    volumes:
      - user_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: p4Y2!qmvDTJd3JzZbjz7
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWTSECRET: nruA/RNh4Xgw7ZiFoGC0Wmd4glv2lK0E0LIWU8EMnMZe5Yt/NV7YrCYmmmpZHWn+x7qztGxbCy/eeVziqwZifA==
      APP_JWTEXPIRATIONMS: 3600000
      SPRING_APPLICATION_JSON: >-
        {
          "eureka": {
            "client": {
              "serviceUrl": {
                "defaultZone": "http://eureka-server:8761/eureka/"
              }
            }
          }
        }
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  user_db_data: