services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_JWTSECRET: nruA/RNh4Xgw7ZiFoGC0Wmd4glv2lK0E0LIWU8EMnMZe5Yt/NV7YrCYmmmpZHWn+x7qztGxbCy/eeVziqwZifA==
      APP_JWTEXPIRATIONMS: 3600000